version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  test-linting:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest
      - run:
          name: Linting
          command: flake8

  build:
    docker:
      - image: cimg/python:3.10
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_REPO:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_REPO:$TAG
    
    deploy:
      docker:
        - image: cimg/python:3.10
          auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
      steps:
          - chekout
          - aws-s3/sync:
            from: bucket
            to: 's3://oclettings/'
            arguments: | 
              --acl public-read \
              --cache-control "max-age=86400"
            overwrite: true         


workflows:
  test-build-deploy:
    jobs:
      - test-linting
      - build:
        requires:
          - test-linting
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master