version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build-test-linting:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest
      - run:
          name: Linting
          command: flake8
  build-docker:
    docker:
      - image: cimg/python:3.10
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_REPO:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_REPO:$TAG

workflows:
  master:
    jobs:
      - build-test-linting
      - build-docker:
          requires:
            - build-test-linting
      - aws-ecr/build-and-push-image:
          repo: oclus
          tag: "latest, v0.1.${CIRCLE_BUILD_NUM}"
          dockerfile: Dockerfile
          path: .
          requires: 
            - build-docker