version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  test-linting:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest
      - run:
          name: Linting
          command: flake8

  build:
    docker:
      - image: cimg/python:3.10
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_REPO:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_REPO:$TAG

  deploy-to-aws:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Install AWS CLI
          command: |
            apt-get update && \
            apt-get install -y awscli

      - run:
          name: Configure AWS credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_REGION


workflows:
  deploy:
    jobs:
      - build-test-linting
      - build-docker:
          requires:
            - build-test-linting
      - deploy-to-aws:
          requires:
            - build-docker
          filters:
            branches:
              only:
                - master